### ISSUE TITLE
Intercom 3.0.0 relese task list

### ISSUE THREAD

**Issue by Kaik** [zikula-modules/InterCom#73]
Hi, I think we need task list for things which need to be done or discussed before final version is released. I have recently made some of the re-factoring but module is still in mess and needs lots of attention.
So here is the list.
- [x] migrate to Twig and Symfony forms
- [x] review/update composer.json build.xml readme
- [x] Doctrine
  - [x] check/finish entity 
  - [x] check/finish repository
  - [x] check/finish query builder
- [x] Install and upgrade
  - [x] module installation - default module settings 
  - [x] module upgrade - ~need to be adjusted to current db scheme / integrity checks~ 
  - [x] module removal
- [x] Module administration
  - [x] improve/review module dashboard
  - [x] module settings
  - [x] ~module tools - Util/Tools db integrity check's and fixing~
- [x] Module user functionality
  - [x] inbox, sent, stored... 
  - [x] message
    - [x] send
    - [x] reply
    - [x] forward
    - [x] save, delete
- [x] ~Ajax~ not first release
- [x] Translations
- [x] ~Other~ not first release
  - [x] spam prevention
  - [x] notifications
  - [x] welcome message
  - [x] autoresponder
- [x] ~Block~ next version

**Comment by Kaik** [comment]
Generally, at the moment module is in semi refactored state first release will be mostly "no ajax". I will try do first release before next week if import and fixing will go without problems.

**Comment by Kaik** [comment]
Done 3.0.0 released I have already found one issue and @Portugao probably another. But this is closed.
